apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels: 
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
      - name: department-service-app
        image: soodneeraj/department-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
        
---
apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
  labels:
    app: department-service-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9003
    protocol: TCP
  selector:
    app: department-service-app        